'use strict';
const page=document.body.dataset.page;
let cart=0;
// Metadata only: never collect passwords, email values, or typed search terms.
function record(interaction,detail={}) {
 const event={honeypot:page,interaction,detail,timestamp:new Date().toISOString()};
 console.info('[EvoGuard demo]',event);
 // Only the dedicated preview server enables this local JSONL collector.
 // Connect your existing event API here after matching its schema and bypass rules.
 if(window.EVOGUARD_PREVIEW) fetch('/__demo/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(event)}).catch(()=>console.warn('Preview event could not be saved'));
}
let toastTimer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',2800)}
function modal(title,message){const body=document.querySelector('#detailbody');body.replaceChildren();const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=message;body.append(h,p);document.querySelector('#detail').showModal()}
document.querySelector('.close').onclick=()=>document.querySelector('#detail').close();
document.querySelector('#search').onsubmit=e=>{e.preventDefault();record('search');const term=e.target.querySelector('input').value.trim().toLowerCase();if(page!=='catalog'){location.href='../catalog/';return}let count=0;document.querySelectorAll('.product').forEach(el=>{el.hidden=!el.dataset.product.toLowerCase().includes(term);if(!el.hidden)count++});toast(count? 'Matching products displayed':'No matching products found')};
document.querySelectorAll('[data-action]').forEach(el=>el.onclick=e=>{e.preventDefault();const action=el.dataset.action;record(action);if(action==='cart')modal('My Cart',cart?`${cart} item(s) added. Checkout is currently unavailable.`:'Your cart is empty.');else if(action==='view-all'){document.querySelectorAll('.product').forEach(p=>p.hidden=false);document.querySelector('.products').scrollIntoView({behavior:'smooth',block:'center'})}else if(action==='more')modal('More','Notifications · Customer Care · Download App');else if(action==='forgot')modal('Forgot Password?','Password recovery is currently unavailable. Please try again later.');else if(action==='register')modal('Create an account','Registration is currently unavailable. Please try again later.');else modal(action==='terms'?'Terms of Use':'Privacy Policy','Please contact customer support for assistance.')});
document.querySelectorAll('[data-category]').forEach(el=>el.onclick=()=>{record('category',{category:el.dataset.category});const match=el.dataset.category.split(',')[0].toLowerCase();let count=0;document.querySelectorAll('.product').forEach(p=>{p.hidden=!p.dataset.product.toLowerCase().includes(match);if(!p.hidden)count++});toast(count?'Category selected':'No products available in this category')});
document.querySelectorAll('.product').forEach(el=>el.onclick=()=>{record('product_view',{product:el.dataset.product});modal(el.dataset.product,'Special offers available. Free delivery on eligible orders.');const body=document.querySelector('#detailbody');body.prepend(el.querySelector('img').cloneNode());const add=document.createElement('button');add.className='orange';add.textContent='ADD TO CART';add.onclick=()=>{cart++;document.querySelector('#count').textContent=`(${cart})`;record('add_to_cart',{product:el.dataset.product});document.querySelector('#detail').close();toast('Added to cart')};body.append(add)});
if(page==='catalog'){let slide=0;const banners=['realme-9-pro.webp','oppo-reno7.webp','poco-m4-pro.webp'];for(const [selector,delta] of [['.prev',-1],['.next',1]])document.querySelector(selector).onclick=()=>{slide=(slide+delta+banners.length)%banners.length;document.querySelector('#banner').src='../shared/images/Banners/'+banners[slide];record('banner',{slide})}}
if(page==='login')document.querySelector('#loginform').onsubmit=e=>{e.preventDefault();record('login_attempt');document.querySelector('#loginstatus').textContent='Invalid email or password. Please try again.';e.target.elements.password.value=''};
const demoRows={Orders:[['OD100421','Processing','₹12,999'],['OD100422','Delivered','₹3,290'],['OD100423','Shipped','₹1,499']],Products:[['Mobiles & Accessories','In stock','₹9,999'],['Furniture','In stock','₹3,290']],Users:[['Customer 1001','Active','Customer'],['Customer 1002','Active','Customer']],Reviews:[['Electronics','4 / 5','Approved'],['Furniture','5 / 5','Approved']]};
function renderAdmin(tab){const body=document.querySelector('#adminbody');document.querySelector('#admintitle').textContent=tab;body.replaceChildren();if(tab==='Dashboard'){body.innerHTML='<div class="stats"><div class="stat">Total Amount<strong>₹1,24,890</strong></div><div class="stat">Total Products<strong>24</strong></div><div class="stat">Total Orders<strong>18</strong></div></div><section class="panel"><div class="sectionhead"><h2>Sales Overview</h2></div><div class="bars" aria-label="Sample sales chart"><i style="--h:35%"></i><i style="--h:60%"></i><i style="--h:45%"></i><i style="--h:80%"></i><i style="--h:65%"></i><i style="--h:95%"></i></div></section>';return}if(tab==='Add Product'){body.innerHTML='<form id="addproduct" class="panel" style="padding:24px"><label class="field"><span>Product Name</span><input required></label><label class="field"><span>Price</span><input type="number" min="0" required></label><button class="blue">Create Product</button></form>';body.querySelector('form').onsubmit=e=>{e.preventDefault();record('admin_create_product');toast('Unable to save product. Please try again later.')};return}if(tab==='My Profile'){body.innerHTML='<div class="panel" style="padding:24px">Administrator · Store Management</div>';return}const rows=demoRows[tab]||[];body.innerHTML='<div class="panel tablewrap"><table><thead><tr><th>Record</th><th>Status</th><th>Details</th></tr></thead><tbody></tbody></table></div>';for(const row of rows){const tr=document.createElement('tr');for(const cell of row){const td=document.createElement('td');td.textContent=cell;tr.append(td)}body.querySelector('tbody').append(tr)}}
if(page==='admin'){renderAdmin('Dashboard');document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{record('admin_navigation',{tab:el.dataset.tab});if(el.dataset.tab==='Logout'){location.href='../login/';return}document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===el));renderAdmin(el.dataset.tab)})}
// Read-only capability probe prevents accidental calls to a production logging API.
fetch('/__demo/config').then(r=>r.ok?r.json():{}).then(c=>{window.EVOGUARD_PREVIEW=c.preview===true;record('page_view')}).catch(()=>record('page_view'));
